--SELECT문

SELECT *
FROM EMPLOYEE
WHERE DNO = 2;

SELECT EMPNAME, TITLE, DNO
FROM EMPLOYEE
WHERE EMPNAME LIKE '이%';

SELECT FLOOR
FROM DEPARTMENT
WHERE DEPTNAME='영업' AND DEPATNAME='개발';
--질의가 잘못된 경우 예시

SELECT EMPNAME, SALARY 
FROM EMPLOYEE
WHERE TITLE = '과장' AND DNO = 1;

SELECT EMPNAME, SALARY 
FROM EMPLOYEE
WHERE TITLE = '과장' AND DNO <> 1;

SELECT EMPNAME, TITLE, SALARY 
FROM EMPLOYEE
WHERE SALARY BETWEEN 3000000 AND 4500000;

SELECT EMPNAME, TITLE, SALARY 
FROM EMPLOYEE
WHERE SALARY >= 3000000 AND SALARY <= 4500000;

SELECT *
FROM EMPLOYEE
WHERE DNO IN (1,3);

SELECT EMPNAME, SALARY, SALARY*1.1 AS NEWSALARY
FROM EMPLOYEE
WHERE TITLE = '과장';

--NULL
SELECT EMPNO, EMPNAME
FROM EMPLOYEE
WHERE DNO IS NULL;

--ORDER BY
SELECT SALARY, TITLE, EMPNAME
FROM EMPLOYEE
WHERE DNO=2
ORDER BY SALARY DESC;

--집단함수
SELECT AVG(SALARY)AS AVGSAL, MAX(SALARY)AS MAXSAL
FROM EMPLOYEE;

--그룹화
SELECT DNO, AVG(SALARY)AS AVGSAL, MAX(SALARY)AS MAXSAL
FROM EMPLOYEE
GROUP BY DNO;

--HAVING
SELECT DNO, AVG(SALARY)AS AVGSAL, MAX(SALARY)AS MAXSAL
FROM EMPLOYEE
GROUP BY DNO
HAVING AVG(SALARY)>=2500000;

--합집합(집합연산)
(SELECT DNO FROM EMPLOYEE WHERE EMPNAME = '김창섭')
UNION
(SELECT DEPTNO FROM DEPARTMENT WHERE DEPTNAME ='개발');

--조인
SELECT EMPNAME, DEPTNAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO = D.DEPTNO;

--자체조인
SELECT E.EMPNAME, M.EMPNAME
FROM EMPLOYEE E, EMPLOYEE M
WHERE E.MANAGER = M.EMPNO;

--부질의(중첩질의)
SELECT EMPNAME, TITLE
FROM EMPLOYEE
WHERE TITLE = 
        (SELECT TITLE
        FROM EMPLOYEE
        WHERE EMPNAME='박영권');
        
--이 중첩질의를
SELECT EMPNAME
FROM EMPLOYEE
WHERE DNO IN 
    (SELECT DEPTNO 
    FROM DEPARTMENT 
    WHERE DEPTNAME='영업' OR DEPTNAME = '개발');
--조인질의로 표현가능
SELECT EMPNAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO = D.DEPTNO
        AND (D.DEPTNAME='영업' OR D.DEPTNAME='개발');
    




------------------------------다른 거(수업시간):쥬피터 연동 
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE;

create user seoh identified by seohnii;
drop user seoh;

create user sh identified by lsh;
grant connect, resource, create session, create view to sh;
CREATE TABLE DEPARTMENT (
	DEPTNO		NUMBER	NOT NULL,
	DEPTNAME	CHAR(10),
	FLOOR		NUMBER,
	PRIMARY KEY(DEPTNO)
);

INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);

