--LIKE: 테이블명 검색하여 해당객체 타입 확인
SELECT
    OBJECT_NAME
    ,OBJECT_TYPE
FROM
    USER_OBJECTS
WHERE OBJECT_NAME LIKE '%DEPARTMENT%';

--오브젝트 삭제
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE;

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS PURGE;


--사용자 생성 
--seoh 유저네임, bluesky 유저비번 
create user seoh identified by seohnii;
--view 가상테이블을 만듬 (권한부여)
grant connect, resource, create session, create view to seoh;


-- DEPARTMENT 테이블 생성
CREATE TABLE DEPARTMENT (
	DEPTNO		NUMBER	NOT NULL,
	DEPTNAME	CHAR(10),
	FLOOR		NUMBER,
	PRIMARY KEY(DEPTNO)
);

INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);


-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
	EMPNO	NUMBER	NOT NULL,
	EMPNAME	CHAR(10)	UNIQUE,
	TITLE	CHAR(10)	DEFAULT '사원',
	MANAGER	NUMBER,
	SALARY	NUMBER	CHECK (SALARY < 6000000),
	DNO		NUMBER	DEFAULT 1 CHECK (DNO IN (1,2,3,4)) ,
	PRIMARY KEY(EMPNO),
	FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPTNO) ON DELETE CASCADE
);


INSERT INTO EMPLOYEE VALUES(2106, '김창섭', '대리', 1003, 2500000, 2);
INSERT INTO EMPLOYEE VALUES(3426, '박영권', '과장', 4377, 3000000, 1);
INSERT INTO EMPLOYEE VALUES(3011, '이수민', '부장', 4377, 4000000, 3);
INSERT INTO EMPLOYEE VALUES(1003, '조민희', '과장', 4377, 3000000, 2);
INSERT INTO EMPLOYEE VALUES(3427, '최종철', '사원', 3011, 1500000, 3);
INSERT INTO EMPLOYEE VALUES(1365, '김상원', '사원', 3426, 1500000, 1);
INSERT INTO EMPLOYEE VALUES(4377, '이성래', '이사',  NULL, 5000000, 2);



-- EMP_PLANNING 뷰 생성
CREATE VIEW EMP_PLANNING
AS
SELECT E.EMPNAME, E.TITLE, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO=D.DEPTNO AND D.DEPTNAME='기획';

-- 테이블과 뷰가 데이터베이스에 생성되었는지 확인 
SELECT * FROM tab;

-- 테이블 구조 확인
DESCRIBE DEPARTMENT;

-- 테이블 내용 확인 
SELECT * FROM DEPARTMENT;
